use_frameworks!

target 'Beamer_Example' do
  pod 'Beamer', :path => '../'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.8.2'
  pod 'Crashlytics', '~> 3.11.1'

  target 'Beamer_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
